CREATE PROC FI_SP_ListBeneficiariosPorCliente
    @IdCliente BIGINT
AS
BEGIN
    SELECT ID, CPF, NOME, IDCLIENTE 
    FROM BENEFICIARIOS WITH(NOLOCK) 
    WHERE IDCLIENTE = @IdCliente
    ORDER BY NOME
END